import { useState } from 'react';
import { type Column } from '../api';

interface Props {
  columns: Column[];
  onInsert: (values: Record<string, unknown>) => Promise<void>;
  onClose: () => void;
}

function isAutoGeneratedPk(col: Column): boolean {
  if (!col.pk) return false;
  const type = (col.type ?? '').toUpperCase().split('(')[0].trim();
  const def = (col.default ?? '').toLowerCase();
  if (type === 'INTEGER' || type === 'INT' || type === '') return true;
  if (type === 'SERIAL' || type === 'BIGSERIAL' || type === 'SMALLSERIAL') return true;
  if (def.includes('nextval')) return true;
  return false;
}

function inputType(col: Column): string {
  const t = (col.type ?? '').toUpperCase().split('(')[0].trim();
  if (['INTEGER', 'INT', 'BIGINT', 'SMALLINT', 'TINYINT', 'SERIAL', 'BIGSERIAL'].includes(t)) return 'number';
  if (['REAL', 'FLOAT', 'DOUBLE', 'NUMERIC', 'DECIMAL', 'FLOAT4', 'FLOAT8'].includes(t)) return 'number';
  if (t === 'DATE') return 'date';
  if (t === 'BOOLEAN' || t === 'BOOL') return 'checkbox';
  return 'text';
}

export default function InsertRowModal({ columns, onInsert, onClose }: Props) {
  const editableColumns = columns.filter((c) => !isAutoGeneratedPk(c));

  const [values, setValues] = useState<Record<string, string>>(() => {
    const init: Record<string, string> = {};
    editableColumns.forEach((c) => {
      init[c.name] = c.default != null ? String(c.default) : '';
    });
    return init;
  });

  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setSaving(true);
    try {
      const payload: Record<string, unknown> = {};
      editableColumns.forEach((col) => {
        const raw = values[col.name];
        if (raw === '' || raw === undefined) {
          payload[col.name] = null;
        } else if (inputType(col) === 'number') {
          payload[col.name] = Number(raw);
        } else if (inputType(col) === 'checkbox') {
          payload[col.name] = raw === 'true' || raw === '1' || raw === 'on';
        } else {
          payload[col.name] = raw;
        }
      });
      await onInsert(payload);
      onClose();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Insert failed');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="modal-backdrop" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal-panel">
        <div className="modal-header">
          <span className="modal-title">Insert Row</span>
          <button className="btn-icon" onClick={onClose} title="Close">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18" /><line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {columns.some(isAutoGeneratedPk) && (
          <div className="insert-modal-auto-note">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
            Primary key will be assigned automatically
          </div>
        )}

        <form onSubmit={handleSubmit} className="insert-modal-form">
          <div className="insert-modal-fields">
            {editableColumns.map((col) => (
              <div key={col.name} className="insert-field">
                <label className="insert-field-label">
                  <span className="insert-field-name">{col.name}</span>
                  <span className="insert-field-meta">
                    {col.type || 'ANY'}
                    {col.pk && <span className="insert-field-pk">PK</span>}
                    {col.notnull && !col.pk && <span className="insert-field-required">required</span>}
                  </span>
                </label>
                {inputType(col) === 'checkbox' ? (
                  <select
                    className="insert-field-input"
                    value={values[col.name] ?? ''}
                    onChange={(e) => setValues((v) => ({ ...v, [col.name]: e.target.value }))}
                  >
                    <option value="">NULL</option>
                    <option value="true">true</option>
                    <option value="false">false</option>
                  </select>
                ) : (
                  <input
                    className="insert-field-input"
                    type={inputType(col)}
                    step={inputType(col) === 'number' ? 'any' : undefined}
                    placeholder={col.notnull && !col.pk ? 'required' : 'NULL'}
                    value={values[col.name] ?? ''}
                    onChange={(e) => setValues((v) => ({ ...v, [col.name]: e.target.value }))}
                  />
                )}
              </div>
            ))}

            {editableColumns.length === 0 && (
              <div className="insert-modal-no-cols">
                No editable columns — all columns are auto-generated.
              </div>
            )}
          </div>

          {error && (
            <div className="insert-modal-error">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
              </svg>
              {error}
            </div>
          )}

          <div className="modal-footer">
            <button type="button" className="btn" onClick={onClose} disabled={saving}>
              Cancel
            </button>
            <button
              type="submit"
              className="btn btn-primary"
              disabled={saving || editableColumns.length === 0}
            >
              {saving ? 'Inserting…' : 'Insert Row'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
